# goal is near 'undock' pose with an inverted orientation (i.e., robot ready to dock)
{
  initial_cov_aa: 0.02,
  initial_cov_xx: 0.01,
  initial_cov_yy: 0.01,
  initial_pose_a: 2.9277432,
  initial_pose_x: -1.7737814188,
  initial_pose_y: -0.31319719553
}
