# pose of the undocked robot;
# valid for a docking station located as in "follow the line board", a.k.a. "v3" world version
# adjusted for real world setup
header:
  seq: 0,
  stamp: now
  frame_id: 'map'
pose:
  position:
    x: 2.934
    y: 6.218
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: -0.15536803346720587
    w: 0.9878566566949545
